### PR TITLE
Add native png support

### PR DESCRIPTION
**Pull request by ananthakumaran**

### CODE REVIEW

**Comment by ondrej-tucek** [comment]
@ananthakumaran Thank you for your codes. We will add you to contributors and rebase your branch. After that (asap) it will be necessary to make a refactor. We definitely change a private function `create_png` to more a readable version if you don't mind.

**Comment by ananthakumaran** [comment]
Sure no issue. Let me know if you need anything from my side.

**Comment by arjan** [comment]
Would be nice if this gets merged at some point :-)

**Comment by ondrej-tucek** [comment]
@ananthakumaran On the end we used a different png library bc it's easier to generate png image. I'm just curious, is it possible generate png with `:png` for raw `data` or `rows` binary data and  without using `Agent`? I mean, put the prepared data once in the png options `call` and then just call `png.create(options)`…

**Comment by ananthakumaran** [comment]
> On the end we used a different png library bc it's easier to generate png image

Nice, It looks much more idiomatic.

>  I'm just curious, is it possible generate png with :png for raw data or rows binary data and without using Agent?

The png library seems to be written with files in mind. The usage is straightforward if you want to write the png to a file. But, if you want to capture the binary directly, then Agent + callback seems like a straightforward workaround. I don't think it's possible to do without using some kind of state (Agent).

**Pull request closed without merging**
