### PR TITLE
Alphanumeric QR code encoding support (#1)

### PR DESCRIPTION
**Pull request by mpichette**
Adding alphanumeric support. Tried to create a framework to allow for the remaining modes to be added. The enhancement I would probably make on top of this is to determine based on the string provided to the create method whether the characters are within the alphanumeric character set and preferentially encode them over byte if they fit.

### CODE REVIEW

**Comment by ondrej-tucek** [comment]
Dear @mpichette,

thank you a lot for your contribution. Definitely we want to merge your code to master. Before that, if you don't mind, we would like to change a little...

**Comment by mpichette** [comment]
> Dear @mpichette,
> 
> thank you a lot for your contribution. Definitely we want to merge your code to master. Before that, if you don't mind, we would like to change a little...

Sure! Anything I can help with?

**Comment by ondrej-tucek** [comment]
@mpichette Thank you for your help, that's fine. We were just wondering why you used a macro. We'd like the code to be as clear as possible.

**Comment by mpichette** [comment]
> 

I think I use behaviours because of the commonality of the process between the different encodings.

**Comment by ondrej-tucek** [comment]
@mpichette we get it now, thank you again for your contribution. Now the new version is out..

**Pull request closed without merging**
